### ISSUE TITLE
bin/* needs to pass groceries varible

### ISSUE THREAD

**Issue by tjnz** [learn-co-curriculum/other-hash-methods-code-along#12]
Currently get error 'passing 0 for 1" when trying to run ruby bin/keys to get_the_keys.  Need to pass the groceries variable

**Comment by victhevenot** [comment]
Hey @tjnz,

thanks so much for raising an issue. I think this issue may be resolved already. `bin/keys` does pass in the `groceries` variable to the `get_the_keys` method. In `lib/keys.rb` if you fill `groceries.flatten` into the body of the method, you get the correct output and the test passes. Im going to go ahead and close this issue let me know if you have any other issues with this.
