### ISSUE TITLE
issue with running ruby bin/keys in challenge 1

### ISSUE THREAD

**Issue by miclp** [learn-co-curriculum/other-hash-methods-code-along#16]
I had to update the code in bin/keys to get this to behave the way I think it's supposed to:

`require_relative "../lib/keys.rb"

 groceries = {
  dairy: ["milk", "yogurt", "cheese"],
  vegetable: ["carrots", "broccoli", "cucumbers"],
  meat: ["chicken", "steak", "salmon"],
  grains: ["rice", "pasta"]
 }

puts get_the_keys(groceries)`

... In other words:  I defined the groceries hash in bin/keys and passed this as an argument to #get_the_keys 

Similar issue and fix with bin/values and bin/min.

**Comment by miclp** [comment]
... In other words:  I defined the groceries hash in bin/keys and passed this as an argument to #get_the_keys

**Comment by AnnJohn** [comment]
thanks for raising this @miclp. We'll look into this soon.

**Comment by SophieDeBenedetto** [comment]
all fixed :)
