### ISSUE TITLE
bin file method calls have no arguments

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/other-hash-methods-code-along#2]
This lesson asks students to run the files in the bin folder to test their code. I, for example got this error message when I did that:

..../other-hash-methods-code-along-v-000/lib/values.rb:11:in `get_the_values': wrong number of arguments (0 for 1) (ArgumentError)
    from bin/values:3:in`<main>'

This makes sense because none of the methods in any bin files pass arguments, or have hashes to call on.

**Comment by MsUzoAgu** [comment]
@onyoo and @AnnJohn: issue has been fixed.
