### ISSUE TITLE
ruby bin/values and ruby bin/min also do not work - the files in bin are missing hash and method argument.

### ISSUE THREAD

**Issue by beingy** [learn-co-curriculum/other-hash-methods-code-along#20]
Please see the bin files I just committed for correction. [https://github.com/beingy/other-hash-methods-code-along-v-000/tree/master/bin](url)

**Comment by steveafrost** [comment]
Experienced the same. Thanks for submitting Beingy.

**Comment by SophieDeBenedetto** [comment]
all fixed :)
