### ISSUE TITLE
bin/keys incomplete

### ISSUE THREAD

**Issue by bhabig** [learn-co-curriculum/other-hash-methods-code-along#22]
this may be done on purpose, but there's no mention of doing anything in the bin/keys file in the README.md...

the bin/keys file is missing the hash that passes as the argument, and it is also missing the '(groceries)' argument at the end of the method.

from a student standpoint it would be helpful to reference editing the bin/keys file in the README.md if that is what is intended, otherwise i think the content was just mistakenly left out:)

**Comment by SophieDeBenedetto** [comment]
all fixed :)
