### ISSUE TITLE
Typo on the #min example

### ISSUE THREAD

**Issue by JoeQuattrone** [learn-co-curriculum/other-hash-methods-code-along#26]
On line 8 of the #min example, you write "  => [c: 100] # Because the key :c is lower than :d in alphabetical order. " It should be edited to say "   => [:c, 100] # Because the key :c is lower than :d in alphabetical order. " The typo here is " [c: 100] "

**Comment by sgharms** [comment]
Good eye! Fixed in https://github.com/learn-co-curriculum/other-hash-methods-code-along/commit/d1dd99c79968ab1757da3844c49c20fe63d41efa
