### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jake0988** [learn-co-curriculum/other-hash-methods-code-along#27]
typo, is == in
Lucky for us, we already did this is Challenge 2

Challenge 3: Return the min
Use the #min method to collect the value that comes first alphabetically ("broccoli").

Step 1. Grab all the grocery values
Lucky for us, we already did this is Challenge 2. If we call, groceries.values.flatten we should get back: ["milk", "yogurt", "cheese", "carrots", "broccoli", "cucumbers", "chicken", "steak", "salmon", "rice", "pasta"]

Step 2. Get the minimum value

**Comment by maxwellbenton** [comment]
Hi @jake0988,

This typo has been fixed. Thank you for catching this and taking the time to provide feedback!
