### ISSUE TITLE
Order of instructions is different in readme.md 

### ISSUE THREAD

**Issue by jenjiyi** [learn-co-curriculum/other-hash-methods-code-along#8]
Not really a big deal but Learn.co lists challenges in different order. Challenge 2 references something done in Step 1 but it's really step 3. 

STEP 2. GET THE MINIMUM VALUE

Simply calling .min on what we did in Step 1 should do the trick:

groceries.values.flatten.min
# => "broccoli"

**Comment by AnnJohn** [comment]
thanks @jenjiyi. We changed the order of the readme to be more clear.
