### ISSUE TITLE
bin files not executing

### ISSUE THREAD

**Issue by mystycs** [learn-co-curriculum/other-hash-methods-code-along#9]
none of the bin files are executing. bin files are unaltered but i still pass learn. This is happening for all the bin files, keys,min,values

some errors below:

➜  other-hash-methods-code-along-v-000 git:(master) ✗ ruby bin/keys
/home/nitrous/code/labs/other-hash-methods-code-along-v-000/lib/keys.rb:11:in `get_the_keys': wrong number of arguments (0 for 1) (ArgumentError)
        from bin/keys:3:in`<main>'

**Comment by AnnJohn** [comment]
hi @mystycs thanks of raising this issue. we'll review as soon as we can.

**Comment by AnnJohn** [comment]
hi again, the bin files are running on our end. it's strange that your tests are passing since it looks like there's an argumenterror. I'll keep this issue open, but could you use the Ask a Question tool so that someone from our Learn team can work specifically with your code? Thanks!

**Comment by AnnJohn** [comment]
closing
